-- Consolidated indexes and uniqueness rules.
-- Remove uniqueness rules superseded by the final multi-mess model.
drop index if exists public.cycles_one_active_per_user_idx;
drop index if exists public.cycles_one_pending_per_user_idx;
drop index if exists public.cycles_user_name_unique_idx;
alter table public.push_subscriptions drop constraint if exists push_subscriptions_endpoint_key;
drop index if exists public.push_subscriptions_endpoint_key;

create index if not exists idx_members_user_id on public.members(user_id);
create index if not exists idx_members_created_at on public.members(created_at);
create index if not exists idx_members_user_sort_order on public.members(user_id, sort_order, created_at);
create index if not exists idx_expenses_user_id on public.expenses(user_id);
create index if not exists idx_expenses_date on public.expenses(date);
create index if not exists idx_expenses_type on public.expenses(type);
create index if not exists meal_logs_user_id_idx on public.meal_logs(user_id);
create index if not exists idx_meal_logs_date on public.meal_logs(date);
create index if not exists idx_meal_logs_member_id on public.meal_logs(member_id);
create index if not exists cycles_user_id_idx on public.cycles(user_id);
create index if not exists cycle_deposits_user_id_idx on public.cycle_deposits(user_id);
create index if not exists cycle_deposits_cycle_id_idx on public.cycle_deposits(cycle_id);
create index if not exists changelog_entries_user_id_idx on public.changelog_entries(user_id);
create index if not exists changelog_entries_cycle_id_idx on public.changelog_entries(cycle_id);
create index if not exists changelog_entries_created_at_idx on public.changelog_entries(created_at desc);
create index if not exists notices_user_expires_idx on public.notices(user_id, expires_at desc, created_at desc);
create unique index if not exists profiles_email_unique_idx on public.profiles(lower(email));
create index if not exists profiles_mess_id_idx on public.profiles(mess_id);
create index if not exists messes_creator_id_idx on public.messes(creator_id);
create index if not exists members_mess_id_idx on public.members(mess_id);
create index if not exists members_profile_id_idx on public.members(profile_id);
create unique index if not exists members_mess_profile_unique_idx on public.members(mess_id, profile_id) where profile_id is not null;
create index if not exists cycles_mess_id_idx on public.cycles(mess_id);
create index if not exists cycles_profile_id_idx on public.cycles(profile_id);
create unique index if not exists cycles_one_active_per_mess_idx on public.cycles(mess_id) where status = 'active';
create unique index if not exists cycles_one_pending_per_mess_idx on public.cycles(mess_id) where status = 'pending';
create unique index if not exists cycles_mess_name_unique_idx on public.cycles(mess_id, lower(name)) where mess_id is not null;
create index if not exists expenses_mess_id_idx on public.expenses(mess_id);
create index if not exists expenses_profile_id_idx on public.expenses(profile_id);
create index if not exists expenses_mess_cycle_date_idx on public.expenses(mess_id, cycle_id, date);
create index if not exists meal_logs_mess_id_idx on public.meal_logs(mess_id);
create index if not exists meal_logs_profile_id_idx on public.meal_logs(profile_id);
create index if not exists meal_logs_mess_cycle_date_idx on public.meal_logs(mess_id, cycle_id, date);
alter table if exists public.meal_logs drop constraint if exists meal_logs_member_id_date_key;
alter table if exists public.meal_logs drop constraint if exists meal_logs_member_id_date_cycle_key;
alter table if exists public.meal_logs add constraint meal_logs_member_id_date_cycle_key unique (member_id, date, cycle_id);
create index if not exists cycle_deposits_mess_id_idx on public.cycle_deposits(mess_id);
create index if not exists cycle_deposits_profile_id_idx on public.cycle_deposits(profile_id);
create index if not exists cycle_deposits_mess_cycle_idx on public.cycle_deposits(mess_id, cycle_id);
create index if not exists changelog_entries_mess_id_idx on public.changelog_entries(mess_id);
create index if not exists changelog_entries_profile_id_idx on public.changelog_entries(profile_id);
create index if not exists notices_mess_id_idx on public.notices(mess_id);
create index if not exists notices_profile_id_idx on public.notices(profile_id);
create index if not exists share_links_mess_id_idx on public.share_links(mess_id);
create index if not exists share_links_profile_id_idx on public.share_links(profile_id);
alter table if exists public.share_links drop constraint if exists share_links_pkey;
create unique index if not exists share_links_mess_id_unique_idx on public.share_links(mess_id) where mess_id is not null;
create index if not exists push_subscriptions_mess_id_idx on public.push_subscriptions(mess_id);
create index if not exists push_subscriptions_profile_id_idx on public.push_subscriptions(profile_id);
create index if not exists notification_deliveries_mess_id_idx on public.notification_deliveries(mess_id);
create index if not exists notification_deliveries_profile_id_idx on public.notification_deliveries(profile_id);
create index if not exists expenses_delete_expires_idx on public.expenses(delete_expires_at) where deleted_at is not null;
create index if not exists members_delete_expires_idx on public.members(delete_expires_at) where deleted_at is not null;
create index if not exists cycles_delete_expires_idx on public.cycles(delete_expires_at) where deleted_at is not null;
create index if not exists push_subscriptions_user_audience_idx on public.push_subscriptions(user_id, audience);
create index if not exists push_subscriptions_shared_token_idx on public.push_subscriptions(share_token) where audience = 'shared';
create unique index if not exists push_subscriptions_main_unique_idx on public.push_subscriptions(user_id, endpoint) where audience = 'main' and share_token is null;
create unique index if not exists push_subscriptions_shared_unique_idx on public.push_subscriptions(user_id, share_token, endpoint) where audience = 'shared';
create unique index if not exists notification_deliveries_user_type_dedupe_idx on public.notification_deliveries(user_id, type, dedupe_key);
create index if not exists member_invites_mess_created_idx on public.member_invites(mess_id, created_at desc);
create index if not exists member_invites_target_idx on public.member_invites(target_member_id) where target_member_id is not null;
